### ISSUE TITLE
Could you add me to the list of developers?

### ISSUE THREAD

**Issue by aviwad** [do-not-theme/do-not-theme.github.io#1]
Hello! I'm Avi Wadhwa, and made Organizer (available on flathub). I support this movement, and while my app isn't much 😅, could you add me to the signature list to this? Wonderful initiative :)

**Comment by aviwad** [comment]
https://flathub.org/apps/details/org.librehunt.Organizer

**Comment by bertob** [comment]
Added you, welcome to the initiative :tada:

**Comment by aviwad** [comment]
:D
