### ISSUE TITLE
Adwaita Dark it's Good ?

### ISSUE THREAD

**Issue by Minzords** [do-not-theme/do-not-theme.github.io#11]
If I use Adwaita Dark it's good?

**Comment by Exalm** [comment]
1. If you're not a distro maker, then use whatever you want :) The initiative is only about distros changing defaults, if you just changed theme on your machine, you know you did it, so it's fine.
2. See https://gitlab.gnome.org/GNOME/gtk/issues/1919

I.e. if an app doesn't specifically support dark variant, there may be problems, like the barely readable blue text here:

![Screenshot from 2019-07-19 01-38-59](https://user-images.githubusercontent.com/1510457/61490283-1becb200-a99c-11e9-859e-961211b8a9fe.png)
