### ISSUE TITLE
Stop, please stop.

### ISSUE THREAD

**Issue by kam00t** [do-not-theme/do-not-theme.github.io#16]
This is ridiculous, the Gnome foundation is so f*cking trash right now, first the anti-white code of conduct and now this ? I'm starting to think that it's not about free software anymore but only about personal political beliefs and convictions.
If you don't want your softwares to be themed force the user to use the default theme, oh wait, this reminds me of Windows....

**Comment by bilelmoussaoui** [comment]
Nice.
