### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by Secret-chest** [do-not-theme/do-not-theme.github.io#27]
Just ask distros to make their themes non-breaking and to define all Adwaita variables for compatibility

**Comment by alatiera** [comment]
Even if that was possible, which isn't and you would have known this if you have read up anything on the multi-year long discussions, but let's say for the sake of it that it was possible to do what you are suggesting, there stills a bunch of other things that break ex. having transparent widgets, or black text on black background etc.
